services:
    frontend-dev:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: future-school-dev
        ports:
            - '3001:3000'
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - NEXT_PUBLIC_API_URL=http://localhost:8000/api
            - NODE_ENV=development
        command: npm run dev
        stdin_open: true
        tty: true
        profiles:
            - dev

    frontend-prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://85.198.89.128:8000/api}
        container_name: future-school-prod
        ports:
            - '3000:3000'
        environment:
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://85.198.89.128:8000/api}
            - NODE_ENV=production
        restart: unless-stopped
        profiles:
            - prod
