'use client';
import React, { useMemo } from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from '@fullcalendar/interaction';
import type { EventClickArg } from '@fullcalendar/core';
import { modalController } from '@/lib/modalController';
import type { EventModalData } from '@/lib/modalController';
import './calendar.css';

const now = new Date();
const currentYear = now.getFullYear();
const currentMonth = now.getMonth() + 1;

const sampleEvents = [
    {
        id: '1',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-01`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Выполнить упражнения 1-10 из учебника по математике',
        subject: 'Математика',
        teacher: 'Иванова А.П.',
        time: '14:00',
    },
    {
        id: '2',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-03`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Итоговый экзамен по русскому языку',
        subject: 'Русский язык',
        teacher: 'Петрова М.С.',
        time: '09:00',
    },
    {
        id: '3',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-05`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Контрольная работа по физике',
        subject: 'Физика',
        teacher: 'Сидоров В.К.',
        time: '11:30',
    },
    {
        id: '4',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-07`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по истории России',
        subject: 'История',
        teacher: 'Козлова Е.В.',
        time: '10:00',
    },
    {
        id: '5',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-08`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по английскому языку',
        subject: 'Английский язык',
        teacher: 'Морозова Т.А.',
        time: '13:00',
    },
    {
        id: '6',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-08`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Подготовить доклад по биологии',
        subject: 'Биология',
        teacher: 'Волкова Л.Н.',
        time: '15:30',
    },
    {
        id: '7',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-10`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по химии',
        subject: 'Химия',
        teacher: 'Новиков А.И.',
        time: '12:00',
    },
    {
        id: '8',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-11`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Решить задачи по геометрии',
        subject: 'Математика',
        teacher: 'Иванова А.П.',
        time: '16:00',
    },
    {
        id: '9',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-12`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по литературе',
        subject: 'Литература',
        teacher: 'Петрова М.С.',
        time: '09:30',
    },
    {
        id: '10',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-13`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по географии',
        subject: 'География',
        teacher: 'Смирнов П.О.',
        time: '11:00',
    },
    {
        id: '11',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-13`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по информатике',
        subject: 'Информатика',
        teacher: 'Кузнецов Д.В.',
        time: '14:30',
    },
    {
        id: '12',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-13`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по обществознанию',
        subject: 'Обществознание',
        teacher: 'Лебедева О.М.',
        time: '16:00',
    },
    {
        id: '13',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-15`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Написать сочинение по русскому языку',
        subject: 'Русский язык',
        teacher: 'Петрова М.С.',
        time: '17:00',
    },
    {
        id: '14',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-15`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по алгебре',
        subject: 'Математика',
        teacher: 'Иванова А.П.',
        time: '10:30',
    },
    {
        id: '15',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-17`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по физике',
        subject: 'Физика',
        teacher: 'Сидоров В.К.',
        time: '09:00',
    },
    {
        id: '16',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-18`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Подготовить презентацию по биологии',
        subject: 'Биология',
        teacher: 'Волкова Л.Н.',
        time: '15:00',
    },
    {
        id: '17',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-19`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по химии',
        subject: 'Химия',
        teacher: 'Новиков А.И.',
        time: '12:30',
    },
    {
        id: '18',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-22`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по географии',
        subject: 'География',
        teacher: 'Смирнов П.О.',
        time: '10:00',
    },
    {
        id: '19',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-23`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Решить задачи по физике',
        subject: 'Физика',
        teacher: 'Сидоров В.К.',
        time: '16:30',
    },
    {
        id: '20',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-24`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по истории',
        subject: 'История',
        teacher: 'Козлова Е.В.',
        time: '11:00',
    },
    {
        id: '21',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-25`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по информатике',
        subject: 'Информатика',
        teacher: 'Кузнецов Д.В.',
        time: '13:30',
    },
    {
        id: '22',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-26`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по литературе',
        subject: 'Литература',
        teacher: 'Петрова М.С.',
        time: '10:30',
    },
    {
        id: '23',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-26`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по обществознанию',
        subject: 'Обществознание',
        teacher: 'Лебедева О.М.',
        time: '14:00',
    },
    {
        id: '24',
        title: 'Тест',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-26`,
        backgroundColor: 'rgb(224, 242, 254)',
        borderColor: 'rgb(224, 242, 254)',
        textColor: '#374151',
        display: 'block',
        description: 'Тест по английскому языку',
        subject: 'Английский язык',
        teacher: 'Морозова Т.А.',
        time: '15:30',
    },
    {
        id: '25',
        title: 'Домашнее Задание',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-29`,
        backgroundColor: 'rgb(255, 237, 213)',
        borderColor: 'rgb(255, 237, 213)',
        textColor: '#374151',
        display: 'block',
        description: 'Подготовить проект по географии',
        subject: 'География',
        teacher: 'Смирнов П.О.',
        time: '17:00',
    },
    {
        id: '26',
        title: 'Экзамен',
        start: `${currentYear}-${currentMonth.toString().padStart(2, '0')}-30`,
        backgroundColor: 'rgb(254, 226, 226)',
        borderColor: 'rgb(254, 226, 226)',
        textColor: '#374151',
        display: 'block',
        description: 'Экзамен по биологии',
        subject: 'Биология',
        teacher: 'Волкова Л.Н.',
        time: '09:30',
    },
];

const Calendar = () => {
    const calendarOptions = useMemo(
        () => ({
            plugins: [dayGridPlugin, interactionPlugin],
            initialView: 'dayGridMonth',
            headerToolbar: {
                left: 'title',
                center: '',
                right: 'prev,next',
            },
            height: 'auto',
            aspectRatio: 1.35,
            dayMaxEvents: 5,
            moreLinkClick: 'popover',
            events: sampleEvents,
            eventDisplay: 'block',
            dayHeaderFormat: {
                weekday: 'short' as const,
            },
            titleFormat: {
                month: 'long' as const,
            },
            buttonText: {
                today: 'Сегодня',
                month: 'Месяц',
            },
            selectable: true,
            selectMirror: true,
            weekends: true,
            firstDay: 1, // Monday
            locale: 'ru',
            eventClick: function (eventInfo: EventClickArg) {
                if (eventInfo.event.start) {
                    const eventData: EventModalData = {
                        title: eventInfo.event.title,
                        start: eventInfo.event.start
                            .toISOString()
                            .split('T')[0],
                        subject: eventInfo.event.extendedProps?.subject || '',
                        teacher: eventInfo.event.extendedProps?.teacher || '',
                        time: eventInfo.event.extendedProps?.time || '',
                        description:
                            eventInfo.event.extendedProps?.description || '',
                    };
                    modalController.open('event-modal', eventData);
                }
            },
            dateClick: function (info: any) {
                console.log('Date clicked:', info.dateStr);
            },
            datesSet: function (dateInfo: any) {
                // Handle date changes if needed
            },
        }),
        []
    );

    return (
        <div className="w-full bg-white rounded-lg shadow-sm overflow-hidden">
            <div className="pl-8 pr-6 pt-6">
                <div className="calendar-container">
                    <FullCalendar {...calendarOptions} />
                </div>
            </div>
        </div>
    );
};

export default Calendar;
